### ISSUE TITLE
API 事件運作不正常

### ISSUE THREAD

**Issue by ayaka209** [momocow/node-cq-websocket#1]
注意到現在使用的是
```
this._eventBus.emit('socket.response', WebsocketType.API, JSON.parse(msg.utf8Data))
```
從而api.response事件不能正確執行

**Comment by momocow** [comment]
謝謝你的回報，當初將 api 子事件從 socket 事件中劃分出來沒有做好修正，如有造成困擾深感抱歉Orz
稍後會一並修正 api 事件底下此類的錯誤。

**Comment by momocow** [comment]
0569ac249d99a0cda8462ad5683fdb9e6a33e924
