### ISSUE TITLE
Typescript support.

### ISSUE THREAD

**Issue by momocow** [momocow/node-cq-websocket#18]
RT.

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/node-cq-websocket/blob/ts-support/cq-websocket.d.ts

稍微按 `README.md` 里的说明写了一个声明文件, 可能一些函数的返回值有出入, 如有发现请及时指出. 

事件部分的声明还需要补充(一大堆).

在此回复以防重复工作

**Comment by momocow** [comment]
如果準備好, 可以發個 PR,
我們再來好好 review 一下 😆
