### ISSUE TITLE
CQWebSocket.on(event_type, listener)中的listener是否支持Promise<void>作为返回值？

### ISSUE THREAD

**Issue by xud6** [momocow/node-cq-websocket#25]
在文档中列出了`string | Promise <string> | void`，我认为应该也支持`Promise<void>`

**Comment by momocow** [comment]
@xud6 由於監聽器的返回值會直接作為 `Promise.resolve` 的參數，並且利用 `await` 等待其 Promise 實現，因此事實上 `Promise<void>` 是支持的。

我會在文檔敘述會做出適當的修正。

**Comment by momocow** [comment]
已更新 ts 聲明。 #27
