### ISSUE TITLE
ts定义文件中 CQWebSocket #on(event_type, listener) 返回值未包含Promise<>

### ISSUE THREAD

**Issue by xud6** [momocow/node-cq-websocket#26]
文档中是`string | Promise <string> | void`，ts定义文件内为`string | void`。

结合
https://github.com/momocow/node-cq-websocket/issues/25#issue-362644866
我认为应该为`string | void | Promise <string | void>`

**Comment by momocow** [comment]
或者，若要更精確的描述目前的行為，其 ts 聲明應如下。

因為不光是 `void` ，只要實現值不為 `string` 全部都表示不響應了。

```ts
type NonString = Exclude<any, string>

type MessageEventListener = (event: CQEvent, context: Record<string, any>) => string | NonString | Promise <string>| Promise<NonString>
```

**Comment by spacemeowx2** [comment]
@momocow 

```ts
type NonString = Exclude<any, string>
string | NonString === any
```

**Comment by momocow** [comment]
`NonString` 確實除了 `void` 以外的值都沒什麼意思, 為了不誤導用戶, 就以 `string | void | Promise <void> | Promise <string>`。

**Comment by momocow** [comment]
已更新 ts 聲明。 #27
