### ISSUE TITLE
HelpWanted

### ISSUE THREAD

**Issue by masnn** [momocow/node-cq-websocket#32]
想在网页中使用通知，需要https连接，此时无法使用websocket协议
能否改用wss://进行传输？

**Comment by momocow** [comment]
@masnn 可以參考[測試代碼](https://github.com/momocow/node-cq-websocket/blob/f5679797456b11cb0e2cd6c07f405ac14972d6e8/test/unit/CQWebsocket.test.js#L74)的寫法, 使用 `protocol` `host` `port` 這幾個選項指定遠端 CQHTTP 的 ws 服務器, 或是直接將 `wss:` 寫進 `baseUrl` 選項中。
