### ISSUE TITLE
Wrong version used for browser bundle, the previous version is used

### ISSUE THREAD

**Issue by momocow** [momocow/node-cq-websocket#36]
That is because the browser bundle is built before `semantic-release` which actually bumps the version.

Also need to configure not to bundle irrelevant version of browser files from the `dist/` directory to NPM release.

**Comment by rikakomoe** [comment]
哦乃原来是自己在文件名上写版本的呀
就留一个 cq-websocket.min.js 就可以了吧
CDN 可以指定 NPM Release 的版本的

梨子 <lijiahao99131@gmail.com> 于 2018年10月23日周二 13:27写道：

**Comment by momocow** [comment]
> CDN 可以指定 NPM Release 的版本的

好欸, 原來如此 🎉
