### ISSUE TITLE
Support Vue.js as a Vue plugin

### ISSUE THREAD

**Issue by momocow** [momocow/node-cq-websocket#37]
[Vue plugin reference](https://vuejs.org/v2/guide/plugins.html)

Then the SDK can be used to develope a Vue app (or Vue components), with `this.$bot` or syntaxes like this.

**Comment by rikakomoe** [comment]
why don't those guys mixin <https://vuejs.org/v2/guide/mixins.html> by
themselves?

momocow <notifications@github.com> 于2018年10月25日周四 上午11:36写道：
