### ISSUE TITLE
ES6 import failed

### ISSUE THREAD

**Issue by SettingDust** [momocow/node-cq-websocket#43]
```
import { CQWebSocket } from 'cq-websocket';
         ^^^^^^^^^^^
SyntaxError: The requested module 'cq-websocket' does not provide an export named 'CQWebSocket'
```

暂时用沙雕方式替代
`const CQWebSocket = (await import('cq-websocket')).default.default;`

**Comment by momocow** [comment]
@SettingDust 要在 node 用 ES6 可以考慮 `babel-register` 一下 😄

**Comment by SettingDust** [comment]
> @SettingDust 要在 node 用 ES6 可以考慮 `babel-register` 一下 😄

实验功能已经从node9开始就有了（昨天刚知道），带参数执行node然后就会把mjs文件做es6语法处理 貌似不需要babel（就是不想用）
