### ISSUE TITLE
request.group.invite 事件监听工作不正常

### ISSUE THREAD

**Issue by YKilin** [momocow/node-cq-websocket#7]
监听`request.group.invite`时，我试着邀请机器人入群，而得到的监听器参数`context`为`undefined`

**Comment by momocow** [comment]
@YKilin 這或許是文檔部分的失誤, 我 ctrl + c 太順手沒有修改好。

移除第一個參數 CQEvent 試試
實際上只有 `message` 系列的事件監聽器第一個參數是個 CQEvent。

文檔我會修正為以下型式：
#### `request` 子事件
| 事件類型 | 監聽器參數 | 說明 |
| - | - | - |
| request.friend | `context` object | 私聊消息。 |
| request.group.add | `context` object | 加群請求。 |
| request.group.invite | `context` object | 邀請入群。 |

感謝回報 _(:з」∠)＿

**Comment by YKilin** [comment]
测试OK了2333 \_(:3」∠)_
