### ISSUE TITLE
想问问如何付费？

### ISSUE THREAD

**Issue by zlq4863947** [momocow/node-cq-websocket#78]
感谢作者做这个nice的库，
想问下如何付费？
没有看到怎么收费，还有收费标准、付费服务内容啥的？

**Comment by rikakomoe** [comment]
https://cqp.cc/t/14901

zlq4863947 <notifications@github.com> 于 2019年8月19日周一 22:20写道：

**Comment by zlq4863947** [comment]
哦 3q 知道了 原来pro是付费版
