### ISSUE TITLE
缺失notice.group_ban事件

### ISSUE THREAD

**Issue by CaoMeiYouRen** [momocow/node-cq-websocket#84]
在最新的[coolq-http-api](https://cqhttp.cc/docs/4.13/#/Post?id=%E7%BE%A4%E7%A6%81%E8%A8%80)中新增了群禁言事件，因此如果触发了群禁言事件就会导致UnexpectedContextError
希望考虑修复

**Comment by momocow** [comment]
謝謝回報，會在下一個 minor 版本加入此事件
